name: kooma
description: Kooma is chat message application allowing you to engage with poeple.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  your_splash: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/imgs/

  fonts:
   - family: Roboto
     fonts:
       - asset: fonts/Roboto-Bold.ttf
       - asset: fonts/Roboto-Regular.ttf
   - family: CustomIcons
     fonts:
         - asset: fonts/CustomIcons.ttf

