/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData check_all_big = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_big = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_big_right = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData happy = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData long_left = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_full = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_circle = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
